package USER;
import UI.*;
import DATA.College;

import LOGIN.Signup.*;
import java.util.ArrayList;

import static UI.UI.INNERWIDTH;

public class Admin extends User {
    private String role;

    public Admin(String userID, String lastName, String firstName, String middleInitial, String emailAddress,
                 String password, String address, int postalCode, String birthDate, char sex, String role) {
        super(userID, lastName, firstName, middleInitial, emailAddress, password, address, postalCode, birthDate, sex);

        this.role = role;
    }

    static ArrayList<User> users = User.users;

    public static String AutoGeneratedStudent() {
        int max = 0;
        for (User u : users) {
            String userID = u.getUserID();
            if (userID.startsWith("S")) {
                int number = Integer.parseInt(userID.substring(1));

                if (number > max) {
                    max = number;
                }
            }
        }
        return String.format("S%03d", max + 1);
    }

    static void displayCollege() {
        System.out.println("Total colleges: " + colleges.size());
        for (College c : colleges) {
            System.out.println(c.getCollegeCode() + " : "
                    + College.getCollegeDescription(c));
        }
    }

    static void displayStudent() {
        System.out.println("Total Student: " + colleges.size());
        for (College c : colleges) {
            System.out.println(c.getCollegeCode() + " : "
                    + College.getCollegeDescription(c));
        }
    }



    public static void adminStart(String userID) {
        UI.header("WELCOME ADMIN " + userID);
        System.out.printf("│%-" + innerWidth + "s│%n", " [1] View Request");
        System.out.printf("│%-" + innerWidth + "s│%n", " [2] Manage Colleges");
        System.out.printf("│%-" + innerWidth + "s│%n", " [3] Manage Sections");
        System.out.printf("│%-" + innerWidth + "s│%n", " [4] Manage Students");
        System.out.printf("│%-" + innerWidth + "s│%n", " [5] Manage Faculties");
        System.out.printf("│%-" + innerWidth + "s│%n", " [6] Backup Data");
        System.out.printf("│%-" + innerWidth + "s│%n", " ");
        System.out.printf("│%-" + innerWidth + "s│%n", " [0] Back");
        UI.footer();

        System.out.print("Select > ");
        int choice = in.nextInt();

        switch (choice) {
            case 0: // go back to login/signup choices break;
            case 1: //viewRequest();break;
            case 2: manageColleges();break;
            case 3: manageSection();break;
            case 4: manageStudents();break;
            case 5: // manageFaculties(); break;
            case 6: //  Backup Data break;
            case 7: // exit break;
        }
    }

    // ------------------------------------------------------------//
    static void viewRequest() {
        UI.header("FACULTY REQUEST LIST");

    }
    // ------------------------------------------------------------//
    static void manageColleges() {
        UI.header("MANAGE COLLEGE INFORMATION");
        System.out.printf("│%-" + innerWidth + "s│%n", " [1] Create New College");
        System.out.printf("│%-" + innerWidth + "s│%n", " [2] Delete Existing College");
        System.out.printf("│%-" + innerWidth + "s│%n", " [3] Update Existing College");
        System.out.printf("│%-" + innerWidth + "s│%n", " [4] View All College");
        System.out.printf("│%-" + innerWidth + "s│%n", " ");
        System.out.printf("│%-" + innerWidth + "s│%n", " [0] Back");
        UI.footer();
        System.out.print("Select > ");
        int choice = in.nextInt();
        in.nextLine();

        switch (choice) {
            case 0: adminStart("A001"); break;
            case 1: createCollege();break;
            case 2: deleteCollege();break;
            case 3: updateCollege();break;
            case 4: // viewAllColleges(); break;
            default: System.out.println("Invalid Choice"); manageColleges(); break;
        }
    }

    static ArrayList<College> colleges = College.colleges;
    // verifying before submitting
    // catch that when user input. big letter ang start
    // view all college
    // include in the manage__() auto generated userID();

    public static void createCollege() {
        String title = "CREATING NEW COLLEGE";
        UI.print(title);
        boolean isValid;
        String College_Description;
        String College_Name;

        do {
            System.out.print("  New College Description: ");;
            College_Description = in.nextLine().trim();

            if (College_Description.isBlank() ||
                    !College_Description.toUpperCase().matches("[a-zA-Z ]+")) {
                isValid = false;
                UI.print(" Description is empty or contains numeric or special characters.. Please try again.");
            } else isValid = true;

            for (College e : colleges) {
                if (College_Description.equalsIgnoreCase(College.getCollegeDescription(e))) {
                    UI.print(" College Description already exists. Please try again.");
                    isValid = false;
                    break;
                }
            }
        } while (!isValid);

        do {
            System.out.print("  New College Name: ");;
            College_Name = in.nextLine().toUpperCase().trim();

            if (College_Name.isBlank() || !College_Name.toUpperCase().matches("[A-Z]+")) {
                isValid = false;
                UI.print("College Name is empty or contains numeric or special characters..  Please try again.");
            } else isValid = true;

            for (College e : colleges) {
                if (College_Name.equalsIgnoreCase(e.getCollegeCode())) {
                    UI.print("College Description already exists. Please try again.");
                    isValid = false;
                    break;
                }
            }
        } while (!isValid);

        UI.header(title);
        System.out.printf("│%-" + innerWidth + "s│%n"," College Name: " + College_Name);
        System.out.printf("│%-" + innerWidth + "s│%n"," College Description: " + College_Description);
        System.out.printf("│%-" + innerWidth + "s│%n", " ");
        UI.submitExit();
        System.out.print("Press '/' to submit the changes > ");
        String choice = in.nextLine().toUpperCase().trim();
        switch (choice) {
            case "/": colleges.add(new College(College_Name, College_Description)); UI.print("NEW COLLEGE SUCCESSFULLY ADDED"); break;
            case "X": UI.print("Adding College was Cancelled.."); manageColleges(); break;
        }
        manageColleges();
    }

    public static void deleteCollege() {
        UI.print("DELETING EXISTING COLLEGE");

        String College_Name;
        boolean isValid;

        do {
            System.out.print("  Input Existing College Name(Abbreviation): ");
            College_Name = in.nextLine().trim().toUpperCase();

            if (College_Name.isEmpty() || !College_Name.toUpperCase().matches("[A-Z]+")) {
                UI.print(" Invalid input. Use letters only. Please try again.");
                isValid = false;
            }

            isValid = true;
            boolean found = false;

            for (int x = 0; x < colleges.size(); x++) {
                College e = colleges.get(x);

                if (College_Name.equals(e.getCollegeCode())) {
                    found = true;
                    UI.header("COLLEGE INFORMATION");
                    System.out.printf("│%-" + innerWidth + "s│%n"," College Name: " + e.getCollegeCode());
                    System.out.printf("│%-" + innerWidth + "s│%n"," College Description: " + College.getCollegeDescription(e));
                    System.out.printf("│%-" + innerWidth + "s│%n", " ");
                    UI.deleteExit();
                    System.out.print("Select > ");
                    String num = in.nextLine().toUpperCase().trim();

                    if (num.equals("/")) {
                        String deletedCollege = e.getCollegeCode();
                        colleges.remove(x);

                        UI.print("College " + deletedCollege + " successfully deleted.");
                    } else if (num.equals("X")) {
                        System.out.println("Deletion cancelled.");
                        manageColleges();
                    } else {
                        System.out.println("Invalid choice. Deletion cancelled.");
                        manageColleges();
                    }
                    break;
                }
            }
            if (!found) {
                System.out.println("College not found. Please try again.");
                isValid = false;
            }
        } while (!isValid);

        displayCollege();
    }

    public static void updateCollege() {
        UI.header("UPDATING NEW COLLEGE");
        String College_Description;
        String College_Name;

        System.out.printf("│%-" + innerWidth + "s│%n", " Detail to be updated");
        System.out.printf("│%-" + innerWidth + "s│%n", " [1] College Description");
        System.out.printf("│%-" + innerWidth + "s│%n", " [2] College Name");
        UI.footer();

        System.out.print("Select > ");
        int choice = in.nextInt();
        in.nextLine();
        switch (choice) {
            case 1:
                System.out.print("Input Existing College Name: ");
                College_Name = in.nextLine().toUpperCase().trim();
                boolean found = false;

                String newCollegeDescription;
                for (College c : colleges) {
                    if (College_Name.equals(c.getCollegeCode())) {
                        found = true;
                        UI.header("COLLEGE INFORMATION");
                        System.out.printf("│%-" + innerWidth + "s│%n","College Name: " + c.getCollegeCode());
                        System.out.printf("│%-" + innerWidth + "s│%n","College Description: " + College.getCollegeDescription(c));
                        UI.footer();
                        do {
                            System.out.print("New College Description: ");
                            newCollegeDescription = in.nextLine().trim();

                            if (newCollegeDescription.isBlank() || !newCollegeDescription.matches("[a-zA-Z ]+")) {
                                UI.print("Invalid input. Use letters only. Please try again.");
                                found = false;
                            }

                        } while (newCollegeDescription.isBlank() || !newCollegeDescription.matches("[a-zA-Z ]+"));
                        c.setCollegeDescription(newCollegeDescription);

                        break;
                    }

                }
                if (!found) {
                    System.out.println("College not found.");
                }
                break;

            case 2:
                System.out.print("Input Existing College Description: ");
                College_Description = in.nextLine().trim().toUpperCase().trim();
                found = false;

                String newCollegeName;

                for (College c : colleges) {
                    if (College_Description.equalsIgnoreCase(College.getCollegeDescription(c))) {
                        found = true;
                        UI.header("COLLEGE INFORMATION");
                        System.out.printf("│%-" + innerWidth + "s│%n","College Name: " + c.getCollegeCode());
                        System.out.printf("│%-" + innerWidth + "s│%n","College Description: " + College.getCollegeDescription(c));
                        UI.footer();
                        do {
                            System.out.print("New College Name: ");
                            newCollegeName = in.nextLine().toUpperCase().trim();

                            if (newCollegeName.isBlank() || !newCollegeName.matches("[A-Z]+")) {
                                System.out.println("Invalid input. Use uppercase letters only. Please try again.");
                            }
                        } while (newCollegeName.isBlank() || !newCollegeName.matches("[A-Z]+"));

                        c.setCollegeCode(newCollegeName);
                        UI.print("College " + c.getCollegeCode() + " successfully updated.");
                        break;
                    }
                }
                if (!found) {
                    System.out.println("College not found");
                }
                break;

            default:
                System.out.println("Invalid choice. Please try again.");
                break;

        }
    }

    // ------------------------------------------------------------//
    static void manageSection() {
        UI.header("MANAGE SECTIONS REQUEST");
        System.out.printf("│%-" + innerWidth + "s│%n", " [1] Create New Section");
        System.out.printf("│%-" + innerWidth + "s│%n", " [2] Delete Existing College");
        System.out.printf("│%-" + innerWidth + "s│%n", " [3] Update Existing College");
        System.out.printf("│%-" + innerWidth + "s│%n", " [4] View All College");
        System.out.printf("│%-" + innerWidth + "s│%n", " [5] Back");
        UI.footer();
        System.out.print("Select > ");
        int choice = in.nextInt();
        in.nextLine();

        switch (choice) {
            case 1:
                createCollege();
                break;
            case 2:
                deleteCollege();
                break;
            case 3:
                updateCollege();
                break;
            case 4: // viewAllColleges(); break;
            default:
                System.out.println("invalid choice");
                break;

        }
    }
    // ------------------------------------------------------------//

    static void manageStudents() {
        UI.header("MANAGE SECTIONS REQUEST");
        System.out.println(" [1] Create New Section");
        System.out.println(" [2] Delete Existing College");
        System.out.println(" [3] Update Existing College");
        System.out.println(" [4] View All College");
        System.out.println(" [5] Back");
        System.out.print("Select > ");
        int choice = in.nextInt();
        in.nextLine();

        switch (choice) {
            case 1:
                createStudent();
                break;
            case 2:
                deleteStudent();
                break;
            case 3:
                updateStudent();
                break;
            case 4:// viewAllStudents(); break;
            default:
                System.out.println("invalid choice");
                break;
        }
    }

    static void createStudent() {
        LOGIN.Signup.signUp("Create New Student");
    }

    static void deleteStudent() {
        UI.header("DELETE EXISTING STUDENT PROFILE");
        String userID;
        do {
            System.out.println("Enter User ID: ");
            userID = in.nextLine();

            if (userID.isBlank()) {
                System.out.println("Invalid input. Please try again.");
            }
        } while (!userID.isBlank());

        for (User user : users) {
            if (user.getUserID().equals(userID)) {
                System.out.println("USER INFORMATION");
                System.out.println("User ID: " + user.getUserID());
                System.out.println("User Name: " + user.getUserName());
                System.out.println("Email: " + user.getEmail());
                System.out.println("Password: " + user.getPassword());
                System.out.println("Address : " + user.getAddress());
                System.out.println("Postal Code: " + user.getPostalCode());
                System.out.println("Birth Date: " + user.getBirthDate());
                System.out.println("Sex: " + user.getSex());

                System.out.println("Sure to delete the User's Information?");
                System.out.println("[1] Yes \n[2] No");
                int choice = in.nextInt();
                in.nextLine();
                switch (choice) {
                    case 1:
                        users.remove(user);
                        System.out.println("User successfully deleted.");
                        break;
                    case 2:
                        System.out.println("Deleting User is cancelled");
                        break;
                }
            }
        }
    }

    static void updateStudent() {


        System.out.println("Enter Student ID: ");
        String userID=in.nextLine();
        for (User user : users) {
            if (user.getUserID().equals(userID)) {
                updateProfile(userID);
            } else System.out.println("Invalid input. Please try again.");
        }
    }
}




